server.port=8080

# Ollama settings
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2
spring.ai.ollama.embedding.options.model=nomic-embed-text

# Elasticsearch settings
spring.elasticsearch.uris=http://localhost:9200
spring.ai.vectorstore.elasticsearch.index-name=smart-retail-rag
spring.ai.vectorstore.elasticsearch.dimensions=768
